version: '3.8'

services:

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - fullstack-network

  frontend:
    build:
      context: ./frontend/frontendapp
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - fullstack-network

networks:
  fullstack-network:
    driver: bridge
