
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 145736415520.dkr.ecr.ap-south-1.amazonaws.com/fullstack-backend:latest
        ports:
        - containerPort: 5000  
